name: Alpine Linux

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '48 12 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
 

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup QEMU static args
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build X86_64 initramfs
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Alpine.dockerfile
          build-args: |
            alpine_version=3.15
            alpine_docker_url=docker.io/library/alpine:3.15
            alpine_flavor="lts virt"
            alpine_features="base squashfs network dhcp https"
          #platforms: linux/amd64,linux/arm64,linux/ppc64le
          platforms: linux/amd64
          outputs: |
            build
          tags: alpine-kernel

      - name: Build Raspberry PI initramfs
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Alpine.dockerfile
          build-args: |
            alpine_version=3.15
            alpine_docker_url=docker.io/library/alpine:3.15
            alpine_flavor="rpi lts virt rpi4"
            alpine_features="base squashfs network dhcp https"
          #platforms: linux/amd64,linux/arm64,linux/ppc64le
          platforms: linux/arm64
          outputs: |
            build
          tags: alpine-kernel

      - name: "Upload x86_64 assets to S3"
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: "https://${{ secrets.BUCKET_ENDPOINT }}"
          SOURCE_DIR: 'build/x86_64/boot'
          DEST_DIR: 'x86_64'

      - name: "Upload aarch64 assets to S3"
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: "https://${{ secrets.BUCKET_ENDPOINT }}"
          SOURCE_DIR: 'build/aarch64/boot'
          DEST_DIR: 'aarch64'

  ipxe:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: "docker.io/library/alpine:3.15"
    steps:
      - name: "Add NodeJS"
        run: "apk add --update --no-cache nodejs npm git bash"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Update the alpine package index"
        run: "apk add alpine-sdk xz-dev perl"

      - name: "Checkout iPXE for Raspberry PI"
        run: git clone https://github.com/ipxe/ipxe

      - name: "Checkout iPXE for Raspberry PI"
        run: git clone https://github.com/ipxe/pipxe

      - name: "Install python-pip"
        run: "apk add --no-cache python3 py-pip"

      - name: "Install awscli"
        run: "pip install awscli"

      - name: "Build IPXE"
        run: "cd ipxe/src && make -j$(nproc) bin-x86_64-efi/ipxe.efi bin/undionly.kpxe"

      - name: "Make an IPXE directory"
        run: "mkdir -p /ipxe"

      - name: "Move the files over"
        run: "cp ipxe/src/bin-x86_64-efi/ipxe.efi ipxe/src/bin/undionly.kpxe /ipxe"

      - name: "Upload the artifacts to an S3 bucket"
        run: "aws s3 --endpoint=https://${{ secrets.BUCKET_ENDPOINT }} cp /ipxe s3://${{ secrets.BUCKET_NAME }}/ipxe/ --recursive --acl public-read"
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Add the testing repo so we can download envsubst"
        run: "echo 'https://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories"

      - name: "Add envsubst"
        run: "apk add envsubst"

