name: Test VM creation

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '48 12 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  spin-up-droplet:
    name: Spin up Droplet
    uses: oxide-one/workflow-runner-maker/.github/workflows/spinup.yaml@main
    with:
      name: droplet-${{ github.run_id }}-${{ github.run_number }}
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      do-access-token: ${{ secrets.DO_ACCESS_KEY }}
